// flow-typed signature: b1fcb26725943b89935a8ba3efcd58ac
// flow-typed version: <<STUB>>/@google-cloud/translate_v^4.0.1/flow_v0.98.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/translate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/translate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/translate/build/src/index' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v2/index' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/doc/google/cloud/translation/v3beta1/doc_translation_service' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/doc/google/longrunning/doc_operations' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/doc/google/protobuf/doc_any' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/doc/google/protobuf/doc_timestamp' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/doc/google/rpc/doc_status' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/index' {
  declare module.exports: any;
}

declare module '@google-cloud/translate/build/src/v3beta1/translation_service_client' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/translate/build/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/index'>;
}
declare module '@google-cloud/translate/build/src/v2/index.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v2/index'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/doc/google/cloud/translation/v3beta1/doc_translation_service.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/doc/google/cloud/translation/v3beta1/doc_translation_service'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/doc/google/longrunning/doc_operations.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/doc/google/longrunning/doc_operations'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/doc/google/protobuf/doc_any.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/doc/google/protobuf/doc_any'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/doc/google/protobuf/doc_timestamp.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/doc/google/protobuf/doc_timestamp'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/doc/google/rpc/doc_status.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/doc/google/rpc/doc_status'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/index.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/index'>;
}
declare module '@google-cloud/translate/build/src/v3beta1/translation_service_client.js' {
  declare module.exports: $Exports<'@google-cloud/translate/build/src/v3beta1/translation_service_client'>;
}
